### ISSUE TITLE
Error when there are no roles

### ISSUE THREAD

**Issue by TranquilMarmot** [auth0-extensions/auth0-source-control-extension-tools#78]
This is the same issue as https://github.com/auth0/auth0-deploy-cli/issues/182 but manifesting in a different way.

If a tenant has no roles present, the API will respond with an empty object, `{}`. However, all of auth0's tooling seems to assume that the API will always return an array which is not the case.

When trying to deploy a tenant with no roles using `auth0-deploy-cli`, the following error occurs:

```
(node:26667) UnhandledPromiseRejectionWarning: TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at calcChanges (/my-project/node_modules/auth0-source-control-extension-tools/lib/utils.js:74:13)
    at RoleHandler.processChanges (/my-project/node_modules/auth0-source-control-extension-tools/lib/auth0/handlers/roles.js:161:44)
    at Auth0.runStage (/my-project/node_modules/auth0-source-control-extension-tools/lib/auth0/index.js:58:50)
    at Auth0.processChanges (/my-project/node_modules/auth0-source-control-extension-tools/lib/auth0/index.js:82:5)
    at Object.deploy (/my-project/node_modules/auth0-source-control-extension-tools/lib/deploy.js:26:3)
    at deploy (/my-project/node_modules/auth0-deploy-cli/lib/commands/import.js:71:3)
```

This error is coming from this line: https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/src/auth0/handlers/roles.js#L116

This is because `calcChanges` expects arrays.

It seems like a workaround needs to be added for roles. Or you could actually fix the roles API to return an empty array instead of an empty object when there are no roles so we can stop playing whack-a-mole with your libraries.

**Comment by shawnmclean** [comment]
Hi @TranquilMarmot, thank you for digging in and providing what the source may be. We're looking into what the best way to approach this without breaking any contracts with other clients.
